language: node_js
node_js: 
    - '6.10.3'

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install
  #- npm install --registry=https://registry.npm.taobao.org


stages:
 - name: deploy

jobs:
 include:
   - stage: deploy
     script:
       - node --version
       - npm --version
       - echo "NPM Deploying Started ..."
       - echo "NPM Building Finished."

     deploy:
       provider: npm
       email: wsyimo@qq.com
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         all_branches: true
